version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER_FILE: /run/secrets/tavoo_db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/tavoo_db_pass
      POSTGRES_DB_FILE: /run/secrets/tavoo_db_name
    secrets:
      - tavoo_db_user
      - tavoo_db_pass
      - tavoo_db_name
    ports:
      - '5432:5432'
    networks:
      - tavoo_net
    volumes:
      - tavoo_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $DB_USER -d $DB_NAME']
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: ghcr.io/ressobe/backend-praca-inzynierska:latest
    depends_on:
      - postgres
    environment:
      - PORT=3001
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
    secrets:
      - tavoo_db_user
      - tavoo_db_pass
      - tavoo_db_name
    networks:
      - tavoo_net
    ports:
      - '3001:3001'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  frontend:
    image: ghcr.io/ressobe/frontend-praca-inzynierska:latest
    environment:
      - API_SERVER_URL=http://backend:3001
    networks:
      - tavoo_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.frontend.rule=Host(`145.223.97.58`)'
      - 'traefik.http.services.frontend.loadbalancer.server.port=80'
    depends_on:
      - traefik

  traefik:
    image: traefik:v3.1
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt

networks:
  tavoo_net:
    driver: overlay

volumes:
  tavoo_postgres_data:
    driver: local
  letsencrypt:
    driver: local

secrets:
  tavoo_db_user:
    external: true
  tavoo_db_pass:
    external: true
  tavoo_db_name:
    external: true
