version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER_FILE: /run/secrets/tavoo_db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/tavoo_db_pass
      POSTGRES_DB_FILE: /run/secrets/tavoo_db_name
    secrets:
      - tavoo_db_user
      - tavoo_db_pass
      - tavoo_db_name
    ports:
      - '5432:5432'
    volumes:
      - tavoo_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB']
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: ghcr.io/ressobe/backend-praca-inzynierska:latest
    depends_on:
      - postgres
    environment:
      - PORT=3001
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
    secrets:
      - tavoo_db_user
      - tavoo_db_pass
      - tavoo_db_name
    networks:
      - tavoo_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  frontend:
    image: ghcr.io/ressobe/frontend-praca-inzynierska:latest
    environment:
      - API_SERVER_URL=http://backend:3001
    networks:
      - tavoo_net
    ports:
      - '3000:80'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  tavoo_net:
    driver: overlay

volumes:
  tavoo_postgres_data:
